pub const PATH_ARCHIVO_JSON_PEDIDOS: &str ="pedidos_ejemplo.json";
pub const CANTIDAD_DISPENSADORES: u8 = 6;
pub const CAPACIDAD_CAFE_GRANO: u32 = 5000;
pub const CAPACIDAD_CAFE_MOLIDO: u32 = 250;
pub const CAPACIDAD_LECHE_FRIA: u32 = 5000;
pub const CAPACIDAD_LECHE_ESPUMA: u32 = 100;
pub const CAPACIDAD_AGUA_CALIENTE: u32 = 1000;
pub const CAPACIDAD_CACAO: u32 = 500;
pub const PORCENTAJE_AVISO_BAJA_CANTIDAD: u32 = 15;
pub const MILISEGUNDOS_ENTRE_ESTADISTICAS: u64 = 10;

